// The demo catalogue seeded by db/seed/products.mjs: ten products per category. Brands are made up.
//
// Prices are in cents. `compareAt` is the "was" price (on sale when set). `daysAgo` sets created_at
// relative to the seed run, so "newest" sorting has something to order. `images` are Unsplash photo
// ids (https://images.unsplash.com/photo-<id>), first one is the primary image.

export const products = [
  // ── Audio ────────────────────────────────────────────────────────────────────────────────────
  {
    slug: "halden-aria-anc-wireless-headphones",
    name: "Aria ANC Wireless Headphones",
    brand: "Halden",
    category: "audio",
    shortDescription: "Over-ear noise cancelling headphones with 40-hour battery life and plush memory-foam cushions.",
    description:
      "Aria blocks out the commute, the open-plan office and the cabin hum with eight microphones and adaptive noise cancelling that retunes itself fifty times a second. Custom 40 mm drivers deliver a warm, detailed sound, and a five-minute charge buys you three more hours of listening. Multipoint Bluetooth keeps your laptop and phone connected at the same time, and the earcups fold flat into a slim hard case.",
    price: 29900,
    compareAt: 34900,
    stock: 42,
    rating: 4.7,
    reviewCount: 1284,
    badge: "Bestseller",
    featured: true,
    daysAgo: 120,
    specs: [
      ["Driver", "40 mm dynamic"],
      ["Noise cancelling", "Adaptive, 8 microphones"],
      ["Battery life", "Up to 40 h (ANC on)"],
      ["Charging", "USB-C, 5 min = 3 h"],
      ["Bluetooth", "5.3, multipoint"],
      ["Codecs", "SBC, AAC, LDAC"],
      ["Weight", "254 g"],
    ],
    images: [
      ["1618366712010-f4ae9c647dcb", "Aria headphones in matte black resting on a table"],
      ["1520170350707-b2da59970118", "Close-up of the Aria earcups against a dark background"],
      ["1505740420928-5e560c06d30e", "Aria headphones on a yellow backdrop"],
    ],
  },
  {
    slug: "halden-studio-r1-monitor-headphones",
    name: "Studio R1 Monitor Headphones",
    brand: "Halden",
    category: "audio",
    shortDescription: "Closed-back wired headphones with a flat, honest response for mixing and critical listening.",
    description:
      "The Studio R1 is built for people who need to hear exactly what is in the recording. A neutral tuning, low-distortion 45 mm drivers and closed-back earcups make it equally at home in a home studio, a podcast booth or on a long listening session. The detachable cable locks into place, and every part, from pads to headband, can be replaced.",
    price: 14900,
    compareAt: null,
    stock: 65,
    rating: 4.6,
    reviewCount: 412,
    badge: null,
    featured: false,
    daysAgo: 300,
    specs: [
      ["Type", "Closed-back, over-ear"],
      ["Driver", "45 mm dynamic"],
      ["Frequency response", "5 Hz - 40 kHz"],
      ["Impedance", "38 Ω"],
      ["Cable", "Detachable, 3 m coiled + 1.2 m straight"],
      ["Weight", "290 g"],
    ],
    images: [
      ["1583394838336-acd977736f90", "Studio R1 monitor headphones with their cable on a white surface"],
      ["1484704849700-f032a568e944", "Detail of the R1 metal yoke and leather earcup"],
    ],
  },
  {
    slug: "sonvik-loop-on-ear-wireless-headphones",
    name: "Loop On-Ear Wireless Headphones",
    brand: "Sonvik",
    category: "audio",
    shortDescription: "Light, foldable on-ear headphones with punchy sound and an all-day 50-hour battery.",
    description:
      "Loop is the pair you throw in your bag and forget about until you need it. The on-ear design weighs just 180 g, folds into a pocket-sized pouch and still delivers a lively, bass-forward sound. Fifty hours of playback means charging once a week is plenty, and the soft-touch finish comes in rose gold and cloud white.",
    price: 12900,
    compareAt: 15900,
    stock: 88,
    rating: 4.3,
    reviewCount: 736,
    badge: null,
    featured: false,
    daysAgo: 210,
    specs: [
      ["Type", "On-ear, foldable"],
      ["Driver", "36 mm dynamic"],
      ["Battery life", "Up to 50 h"],
      ["Bluetooth", "5.2"],
      ["Colours", "Rose gold, cloud white"],
      ["Weight", "180 g"],
    ],
    images: [
      ["1545127398-14699f92334b", "Loop headphones in rose gold"],
      ["1491927570842-0261e477d937", "Loop headphones in cloud white floating in mid-air"],
    ],
  },
  {
    slug: "sonvik-pulse-pro-true-wireless-earbuds",
    name: "Pulse Pro True Wireless Earbuds",
    brand: "Sonvik",
    category: "audio",
    shortDescription: "Compact noise cancelling earbuds with spatial audio and a wireless charging case.",
    description:
      "Pulse Pro packs active noise cancelling, a transparency mode and spatial audio into earbuds that disappear in your ears. Three sizes of silicone tips and a pressure-relief vent keep them comfortable for hours, and the pocketable case adds four full charges. IPX4 sweat resistance makes them a solid gym companion too.",
    price: 17900,
    compareAt: null,
    stock: 130,
    rating: 4.5,
    reviewCount: 2210,
    badge: "Bestseller",
    featured: true,
    daysAgo: 95,
    specs: [
      ["Noise cancelling", "Active, with transparency mode"],
      ["Battery life", "6 h buds + 24 h case"],
      ["Charging", "USB-C, Qi wireless"],
      ["Water resistance", "IPX4"],
      ["Bluetooth", "5.3"],
      ["Weight", "5.3 g per bud"],
    ],
    images: [
      ["1572569511254-d8f925fe2cbb", "Pulse Pro earbuds in their open charging case"],
      ["1606741965326-cb990ae01bb2", "Pulse Pro earbuds lying next to the case"],
      ["1505236273191-1dce886b01e9", "Pulse Pro case on a white desk"],
    ],
  },
  {
    slug: "corda-stride-sport-earbuds",
    name: "Stride Sport Earbuds",
    brand: "Corda",
    category: "audio",
    shortDescription: "Secure-fit sport earbuds with IP57 protection and a bass boost tuned for training.",
    description:
      "Stride is designed for runs, rides and rainy-day workouts. Wing tips lock each bud in place, IP57 sealing shrugs off sweat and downpours, and a dedicated bass boost keeps your playlist driving. Physical buttons work with gloves on, and a quick ten-minute charge gives you a full hour of training.",
    price: 7900,
    compareAt: 9900,
    stock: 0,
    rating: 4.2,
    reviewCount: 389,
    badge: null,
    featured: false,
    daysAgo: 160,
    specs: [
      ["Fit", "Wing tips, 3 sizes"],
      ["Battery life", "8 h buds + 22 h case"],
      ["Water resistance", "IP57"],
      ["Controls", "Physical buttons"],
      ["Bluetooth", "5.2"],
    ],
    images: [
      ["1606220945770-b5b6c2c55bf1", "Stride sport earbuds in black on a blue surface"],
      ["1606220588913-b3aacb4d2f46", "Stride earbuds beside their charging case under red light"],
      ["1590658268037-6bf12165a8df", "Stride earbuds in black and white finishes with their cases"],
    ],
  },
  {
    slug: "marlowe-trailblazer-portable-speaker",
    name: "Trailblazer Portable Speaker",
    brand: "Marlowe Audio",
    category: "audio",
    shortDescription: "Rugged, waterproof Bluetooth speaker with big stereo sound and 20 hours of play.",
    description:
      "Trailblazer brings room-filling sound to the beach, the campsite and the back garden. Twin passive radiators give it real low end, the IP67 shell survives drops and dunks, and it floats if it ends up in the lake. Pair two units for true stereo, or use the built-in power bank to top up your phone.",
    price: 14900,
    compareAt: null,
    stock: 54,
    rating: 4.6,
    reviewCount: 958,
    badge: null,
    featured: false,
    daysAgo: 75,
    specs: [
      ["Output", "2 × 15 W"],
      ["Battery life", "Up to 20 h"],
      ["Water resistance", "IP67, floats"],
      ["Stereo pairing", "Yes"],
      ["Power bank", "USB-C out"],
      ["Weight", "960 g"],
    ],
    images: [
      ["1608043152269-423dbba4e7e1", "Trailblazer speaker in black on a wooden table"],
      ["1589003077984-894e133dabab", "Trailblazer speaker lit with colourful light"],
      ["1588131153911-a4ea5189fe19", "Compact Trailblazer Go with a carabiner loop"],
    ],
  },
  {
    slug: "marlowe-pebble-mini-speaker",
    name: "Pebble Mini Speaker",
    brand: "Marlowe Audio",
    category: "audio",
    shortDescription: "Pocket-sized Bluetooth speaker with a leather strap and surprisingly full sound.",
    description:
      "Pebble is small enough for a jacket pocket and handsome enough to leave out on the shelf. A custom full-range driver and a passive radiator squeeze out more sound than its size suggests, the vegan leather strap makes it easy to hang anywhere, and the battery lasts a full day of background music.",
    price: 5900,
    compareAt: 7900,
    stock: 120,
    rating: 4.1,
    reviewCount: 274,
    badge: "New",
    featured: false,
    daysAgo: 6,
    specs: [
      ["Output", "5 W"],
      ["Battery life", "Up to 12 h"],
      ["Water resistance", "IPX5"],
      ["Bluetooth", "5.3"],
      ["Weight", "240 g"],
    ],
    images: [
      ["1582978571763-2d039e56f0c3", "Pebble Mini speaker in white with a leather strap on a wooden table"],
      ["1547052178-7f2c5a20c332", "Pebble Mini in grey on a white surface"],
    ],
  },
  {
    slug: "marlowe-model-two-bookshelf-speakers",
    name: "Model Two Bookshelf Speakers",
    brand: "Marlowe Audio",
    category: "audio",
    shortDescription: "Powered bookshelf speakers with walnut veneer, HDMI ARC and a built-in phono stage.",
    description:
      "Model Two turns any room into a listening room. Each cabinet houses a silk-dome tweeter and a 5.25-inch woven woofer driven by its own amplifier, so all you add is a source. Plug in a turntable thanks to the built-in phono stage, connect your TV over HDMI ARC, or stream from your phone. Real walnut veneer and magnetic grilles finish the look.",
    price: 49900,
    compareAt: null,
    stock: 18,
    rating: 4.8,
    reviewCount: 207,
    badge: "Staff pick",
    featured: true,
    daysAgo: 45,
    specs: [
      ["Amplification", "2 × 50 W class D"],
      ["Drivers", "1\" silk tweeter, 5.25\" woofer"],
      ["Inputs", "HDMI ARC, optical, phono, RCA, Bluetooth"],
      ["Finish", "Walnut veneer"],
      ["Dimensions", "29 × 18 × 24 cm each"],
    ],
    images: [
      ["1545454675-3531b543be5d", "Model Two bookshelf speaker with the grille removed"],
      ["1609702847389-b8aec1b0b929", "Pair of Model Two speakers on a wooden desk"],
      ["1595432541891-a461100d3054", "Model Two speakers in a listening room"],
    ],
  },
  {
    slug: "corda-groove-belt-drive-turntable",
    name: "Groove Belt-Drive Turntable",
    brand: "Corda",
    category: "audio",
    shortDescription: "Belt-drive turntable with a pre-mounted cartridge, carbon tonearm and switchable preamp.",
    description:
      "Groove gets you from box to first record in five minutes. The belt-drive platter isolates motor noise, the carbon-fibre tonearm arrives balanced with a moving-magnet cartridge already fitted, and the switchable preamp lets you plug straight into powered speakers or a proper amplifier. It plays 33 and 45 RPM at the press of a button.",
    price: 34900,
    compareAt: 39900,
    stock: 23,
    rating: 4.5,
    reviewCount: 341,
    badge: null,
    featured: false,
    daysAgo: 180,
    specs: [
      ["Drive", "Belt"],
      ["Speeds", "33⅓, 45 RPM"],
      ["Tonearm", "Carbon fibre, 8.6\""],
      ["Cartridge", "Moving magnet, pre-mounted"],
      ["Preamp", "Built-in, switchable"],
    ],
    images: [
      ["1616681255209-368a2cd3e643", "Groove turntable tonearm over a red vinyl record"],
      ["1542395118-9d95347995bc", "Blue record spinning on the Groove turntable"],
      ["1496293455970-f8581aae0e3b", "Groove turntable on a sideboard next to records"],
    ],
  },
  {
    slug: "halden-podcaster-usb-condenser-microphone",
    name: "Podcaster USB Condenser Microphone",
    brand: "Halden",
    category: "audio",
    shortDescription: "Studio-quality USB microphone with a cardioid capsule, shock mount and zero-latency monitoring.",
    description:
      "Podcaster captures broadcast-quality voice without an audio interface. The 25 mm cardioid capsule focuses on what is in front of it and rejects the room, the included shock mount isolates desk bumps, and the headphone output lets you hear yourself with zero latency. Plug it in over USB-C and it works with every recording and streaming app.",
    price: 12900,
    compareAt: null,
    stock: 47,
    rating: 4.4,
    reviewCount: 523,
    badge: "New",
    featured: false,
    daysAgo: 12,
    specs: [
      ["Capsule", "25 mm condenser"],
      ["Polar pattern", "Cardioid"],
      ["Resolution", "24-bit / 96 kHz"],
      ["Connection", "USB-C"],
      ["Monitoring", "3.5 mm, zero latency"],
    ],
    images: [
      ["1660631228116-b3643559f611", "Podcaster microphone in its shock mount on a boom arm"],
      ["1531651008558-ed1740375b39", "Podcaster microphone behind a pop filter"],
    ],
  },

  // ── Watches ──────────────────────────────────────────────────────────────────────────────────
  {
    slug: "calder-heritage-open-heart-automatic",
    name: "Heritage Open Heart Automatic",
    brand: "Calder",
    category: "watches",
    shortDescription: "Automatic dress watch with an open-heart dial and a brown Italian leather strap.",
    description:
      "The Heritage shows off its beating heart through a window at nine o'clock, where you can watch the balance wheel swing back and forth. A cream sunray dial, blued hands and a polished 40 mm case give it a classic feel, while the exhibition caseback reveals the rest of the automatic movement. It comes on a hand-stitched Italian leather strap.",
    price: 42900,
    compareAt: null,
    stock: 14,
    rating: 4.8,
    reviewCount: 186,
    badge: null,
    featured: false,
    daysAgo: 140,
    specs: [
      ["Movement", "Automatic, 41 h power reserve"],
      ["Case", "40 mm stainless steel"],
      ["Crystal", "Sapphire, anti-reflective"],
      ["Water resistance", "50 m"],
      ["Strap", "Brown Italian leather, 20 mm"],
    ],
    images: [
      ["1524805444758-089113d48a6d", "Heritage open-heart watch on a brown leather strap"],
      ["1539874754764-5a96559165b0", "Heritage chronograph variant on a red background"],
    ],
  },
  {
    slug: "nordhavn-abyss-300-dive-watch",
    name: "Abyss 300 Dive Watch",
    brand: "Nordhavn",
    category: "watches",
    shortDescription: "300 m automatic diver with a ceramic bezel, lume-packed dial and screw-down crown.",
    description:
      "Abyss 300 is a proper tool watch: 300 metres of water resistance, a unidirectional ceramic bezel that won't fade, and hands and markers filled with Super-LumiNova that glow for hours. The brushed steel bracelet has an on-the-fly extension for wearing over a wetsuit, and the automatic movement needs no battery, ever.",
    price: 54900,
    compareAt: 64900,
    stock: 9,
    rating: 4.7,
    reviewCount: 248,
    badge: "Bestseller",
    featured: true,
    daysAgo: 230,
    specs: [
      ["Movement", "Automatic, 70 h power reserve"],
      ["Case", "42 mm stainless steel"],
      ["Bezel", "Unidirectional ceramic"],
      ["Water resistance", "300 m"],
      ["Lume", "Super-LumiNova BGW9"],
      ["Bracelet", "Steel, quick-extension clasp"],
    ],
    images: [
      ["1603850179998-3a57f293b2c5", "Abyss 300 with a black dial on a dark background"],
      ["1662384197911-e82189f4dc60", "Abyss 300 on its steel bracelet"],
      ["1620421895918-b4e8c86648fb", "Abyss 300 with a white dial on a NATO strap"],
    ],
  },
  {
    slug: "nordhavn-tidewater-blue-diver",
    name: "Tidewater Blue Diver",
    brand: "Nordhavn",
    category: "watches",
    shortDescription: "Blue-dial automatic diver with a sunburst finish and a stainless steel bracelet.",
    description:
      "Tidewater pairs a deep blue sunburst dial with a matching bezel, so it changes from navy to electric blue as the light moves across it. Underneath is a reliable automatic movement, a 200 m rated case and a solid-link bracelet that wears comfortably from the beach to the boardroom.",
    price: 38900,
    compareAt: null,
    stock: 21,
    rating: 4.6,
    reviewCount: 132,
    badge: null,
    featured: false,
    daysAgo: 60,
    specs: [
      ["Movement", "Automatic, 41 h power reserve"],
      ["Case", "41 mm stainless steel"],
      ["Dial", "Blue sunburst"],
      ["Water resistance", "200 m"],
      ["Bracelet", "Solid-link steel"],
    ],
    images: [
      ["1607850478432-a80d4ff5aa41", "Tidewater diver with a blue dial resting on a rock"],
      ["1542816340-4d3de5047cfd", "Tidewater chronograph worn on the wrist"],
      ["1523170335258-f5ed11844a49", "Tidewater chronograph dial close-up"],
    ],
  },
  {
    slug: "calder-meridian-blue-dial-automatic",
    name: "Meridian Blue Dial Automatic",
    brand: "Calder",
    category: "watches",
    shortDescription: "Everyday automatic with a deep blue dial, date window and integrated bracelet.",
    description:
      "Meridian is the one watch that goes with everything. Its 39 mm case sits well on most wrists, the gradient blue dial has applied indices that catch the light, and the integrated bracelet tapers neatly to a butterfly clasp. A date at three and a sapphire crystal round out a watch built for daily wear.",
    price: 32900,
    compareAt: 37900,
    stock: 27,
    rating: 4.5,
    reviewCount: 211,
    badge: null,
    featured: false,
    daysAgo: 85,
    specs: [
      ["Movement", "Automatic, date"],
      ["Case", "39 mm stainless steel"],
      ["Crystal", "Sapphire"],
      ["Water resistance", "100 m"],
      ["Bracelet", "Integrated steel, butterfly clasp"],
    ],
    images: [
      ["1636639818651-d97365346a5c", "Meridian with a blue dial on a black background"],
      ["1547996160-81dfa63595aa", "Meridian with a grey dial on its steel bracelet"],
      ["1587836374828-4dbafa94cf0e", "Meridian with a black dial in close-up"],
    ],
  },
  {
    slug: "ostara-classique-dress-watch",
    name: "Classique Dress Watch",
    brand: "Ostara",
    category: "watches",
    shortDescription: "Slim two-tone dress watch with a silver dial, fluted bezel and jubilee-style bracelet.",
    description:
      "Classique is a modern take on a mid-century dress watch. The silver dial is kept clean, with slim baton indices and a cyclops-magnified date, framed by a fluted bezel in warm yellow-gold PVD. At just 9 mm thick it slides easily under a shirt cuff.",
    price: 27900,
    compareAt: null,
    stock: 16,
    rating: 4.4,
    reviewCount: 98,
    badge: null,
    featured: false,
    daysAgo: 270,
    specs: [
      ["Movement", "Swiss quartz"],
      ["Case", "36 mm, two-tone steel"],
      ["Thickness", "9 mm"],
      ["Water resistance", "50 m"],
      ["Bracelet", "Jubilee-style, two-tone"],
    ],
    images: [
      ["1620625515032-6ed0c1790c75", "Classique dress watch with a silver dial"],
      ["1619976491498-f2dadb25fb3b", "Classique on a dark wooden surface"],
    ],
  },
  {
    slug: "ostara-regent-gold-chronograph",
    name: "Regent Gold Chronograph",
    brand: "Ostara",
    category: "watches",
    shortDescription: "Gold-tone chronograph with a tachymeter bezel and three sub-dials.",
    description:
      "Regent is a statement chronograph inspired by 1960s racing watches. A gold-tone case and bracelet frame a black dial with three contrasting sub-dials, and the tachymeter bezel lets you time laps or measure speed. The quartz chronograph movement is accurate to a tenth of a second.",
    price: 34900,
    compareAt: 44900,
    stock: 11,
    rating: 4.3,
    reviewCount: 77,
    badge: "Limited",
    featured: false,
    daysAgo: 30,
    specs: [
      ["Movement", "Quartz chronograph, 1/10 s"],
      ["Case", "40 mm, gold-tone steel"],
      ["Bezel", "Tachymeter"],
      ["Water resistance", "100 m"],
      ["Bracelet", "Gold-tone steel"],
    ],
    images: [
      ["1587925358603-c2eea5305bbc", "Regent gold chronograph on a reflective surface"],
      ["1600003014637-ff82a275e191", "Regent chronograph with a black dial"],
      ["1579543768549-96d37c1df78f", "Regent chronograph in its presentation box"],
    ],
  },
  {
    slug: "ostara-rosalind-rose-gold-watch",
    name: "Rosalind Rose Gold Watch",
    brand: "Ostara",
    category: "watches",
    shortDescription: "Rose-gold automatic with a chocolate dial and a coin-edge bezel.",
    description:
      "Rosalind pairs a rich chocolate sunburst dial with a rose-gold PVD case and coin-edge bezel. The automatic movement is visible through the sapphire caseback, and the five-link bracelet is finished with alternating polished and brushed surfaces. It is the kind of watch you dress up for.",
    price: 46900,
    compareAt: null,
    stock: 7,
    rating: 4.9,
    reviewCount: 54,
    badge: "Limited",
    featured: true,
    daysAgo: 20,
    specs: [
      ["Movement", "Automatic, 42 h power reserve"],
      ["Case", "38 mm, rose-gold PVD"],
      ["Dial", "Chocolate sunburst"],
      ["Water resistance", "50 m"],
      ["Bracelet", "Five-link, rose-gold PVD"],
    ],
    images: [
      ["1600003014755-ba31aa59c4b6", "Rosalind rose-gold watch with a chocolate dial"],
      ["1600003014608-c2ccc1570a65", "Rosalind dial and bezel in close-up"],
      ["1623998021661-dc7555b2213d", "Rosalind with a blue dial on a white surface"],
    ],
  },
  {
    slug: "calder-pilot-smoke-chronograph",
    name: "Pilot Smoke Chronograph",
    brand: "Calder",
    category: "watches",
    shortDescription: "Gunmetal chronograph with a smoked dial and a matching mesh-free strap.",
    description:
      "Pilot Smoke wraps a quartz chronograph in a gunmetal IP-coated case with a smoked bronze dial. Oversized numerals keep it legible at a glance, the 45-minute counter is ideal for timing flights or meetings, and the brushed finish hides everyday scuffs.",
    price: 19900,
    compareAt: 24900,
    stock: 33,
    rating: 4.2,
    reviewCount: 143,
    badge: null,
    featured: false,
    daysAgo: 330,
    specs: [
      ["Movement", "Quartz chronograph"],
      ["Case", "44 mm, gunmetal IP steel"],
      ["Crystal", "Mineral"],
      ["Water resistance", "100 m"],
    ],
    images: [
      ["1622434641406-a158123450f9", "Pilot Smoke chronograph with a gunmetal case"],
      ["1610897534349-7759782118b9", "Pilot Smoke on a dark fabric"],
    ],
  },
  {
    slug: "pulse-active-2-smartwatch",
    name: "Active 2 Smartwatch",
    brand: "Pulse",
    category: "watches",
    shortDescription: "Always-on AMOLED smartwatch with GPS, heart-rate tracking and a week of battery.",
    description:
      "Active 2 tracks more than 100 workout types with dual-band GPS, continuous heart rate and blood-oxygen readings. The always-on AMOLED display is bright enough for midday runs, notifications and contactless payments are a glance away, and a full charge lasts seven days of typical use.",
    price: 24900,
    compareAt: null,
    stock: 76,
    rating: 4.4,
    reviewCount: 1675,
    badge: "Bestseller",
    featured: true,
    daysAgo: 50,
    specs: [
      ["Display", "1.9\" AMOLED, always-on"],
      ["GPS", "Dual-band"],
      ["Sensors", "Heart rate, SpO2, skin temperature"],
      ["Battery life", "Up to 7 days"],
      ["Water resistance", "5 ATM"],
    ],
    images: [
      ["1546868871-7041f2a55e12", "Active 2 smartwatch in space grey with a black sport band"],
      ["1551816230-ef5deaed4a26", "Active 2 showing its app grid on a white desk"],
      ["1624096104992-9b4fa3a279dd", "Active 2 on a white background"],
    ],
  },
  {
    slug: "pulse-air-smartwatch",
    name: "Air Smartwatch",
    brand: "Pulse",
    category: "watches",
    shortDescription: "Lightweight aluminium smartwatch with sleep tracking and a soft sport band.",
    description:
      "Air is the smartwatch for people who forget they are wearing one. The aluminium case weighs 26 g, the soft sport band is comfortable overnight for detailed sleep tracking, and the bright display shows messages, calls and timers at a glance. It works with both iPhone and Android.",
    price: 17900,
    compareAt: 19900,
    stock: 58,
    rating: 4.1,
    reviewCount: 642,
    badge: "New",
    featured: false,
    daysAgo: 3,
    specs: [
      ["Display", "1.7\" OLED"],
      ["Case", "40 mm aluminium, 26 g"],
      ["Sensors", "Heart rate, accelerometer"],
      ["Battery life", "Up to 4 days"],
      ["Compatibility", "iOS and Android"],
    ],
    images: [
      ["1617043983671-adaadcaa2460", "Air smartwatch in white"],
      ["1434493789847-2f02dc6ca35d", "Air smartwatch worn on the wrist"],
      ["1517420879524-86d64ac2f339", "Air smartwatch held up showing its apps"],
    ],
  },

  // ── Footwear ─────────────────────────────────────────────────────────────────────────────────
  {
    slug: "strider-velocity-knit-running-shoe",
    name: "Velocity Knit Running Shoe",
    brand: "Strider",
    category: "footwear",
    shortDescription: "Lightweight road running shoe with a breathable knit upper and responsive foam.",
    description:
      "Velocity is built for tempo days and race days. A one-piece knit upper wraps the foot like a sock, the nitrogen-infused midsole returns energy with every stride, and a rubber outsole places grip only where you need it. At 230 g it feels fast the moment you lace up.",
    price: 13900,
    compareAt: null,
    stock: 64,
    rating: 4.6,
    reviewCount: 892,
    badge: "Bestseller",
    featured: true,
    daysAgo: 110,
    specs: [
      ["Upper", "Engineered knit"],
      ["Midsole", "Nitrogen-infused foam"],
      ["Drop", "8 mm"],
      ["Weight", "230 g (US 9)"],
      ["Use", "Road running"],
    ],
    images: [
      ["1542291026-7eec264c27ff", "Velocity knit running shoe in red"],
      ["1469395446868-fb6a048d5ca3", "Velocity running shoes held up in a field"],
      ["1562183241-b937e95585b6", "Velocity running shoe in grey mid-stride"],
    ],
  },
  {
    slug: "strider-cloudride-daily-trainer",
    name: "Cloudride Daily Trainer",
    brand: "Strider",
    category: "footwear",
    shortDescription: "Max-cushioned daily trainer with a visible air unit and a retro colourway.",
    description:
      "Cloudride is the everyday shoe for easy miles, long walks and standing all day. A thick foam midsole with a visible air unit soaks up impact, the mesh-and-suede upper breathes well, and the cream-and-coral colourway nods to 90s runners without looking like a costume.",
    price: 11900,
    compareAt: 14900,
    stock: 81,
    rating: 4.4,
    reviewCount: 547,
    badge: null,
    featured: false,
    daysAgo: 150,
    specs: [
      ["Upper", "Mesh and suede"],
      ["Midsole", "Foam with air unit"],
      ["Drop", "10 mm"],
      ["Weight", "310 g (US 9)"],
      ["Use", "Daily training, walking"],
    ],
    images: [
      ["1600185365483-26d7a4cc7519", "Cloudride trainer in cream and coral"],
      ["1600185365926-3a2ce3cdb9eb", "Cloudride trainer side view"],
      ["1608667508764-33cf0726b13a", "Cloudride Lite in pink and peach"],
    ],
  },
  {
    slug: "kinetic-gel-stability-runner",
    name: "Gel Stability Runner",
    brand: "Kinetic",
    category: "footwear",
    shortDescription: "Supportive stability shoe with gel cushioning for overpronators and long distances.",
    description:
      "Gel Stability Runner guides your foot through each step with a firmer medial post, while gel pods in the heel and forefoot take the edge off long runs. The reinforced heel counter locks you in, and a durable carbon-rubber outsole is good for hundreds of miles.",
    price: 14900,
    compareAt: null,
    stock: 39,
    rating: 4.5,
    reviewCount: 418,
    badge: null,
    featured: false,
    daysAgo: 200,
    specs: [
      ["Upper", "Engineered mesh"],
      ["Support", "Medial post"],
      ["Cushioning", "Heel and forefoot gel"],
      ["Drop", "10 mm"],
      ["Weight", "300 g (US 9)"],
    ],
    images: [
      ["1709258228137-19a8c193be39", "Gel Stability Runner in silver grey"],
      ["1571008887538-b36bb32f4571", "Runner wearing Gel Stability shoes on a track"],
    ],
  },
  {
    slug: "fenwick-court-classic-leather-sneaker",
    name: "Court Classic Leather Sneaker",
    brand: "Fenwick & Co",
    category: "footwear",
    shortDescription: "Minimal white leather sneaker with a cupsole and a cushioned footbed.",
    description:
      "Court Classic is the clean white sneaker that goes with jeans, chinos and suits alike. Full-grain leather softens with wear, a stitched rubber cupsole keeps it in shape for years, and the removable cork footbed moulds to your foot. It is made in Portugal in small batches.",
    price: 15900,
    compareAt: null,
    stock: 72,
    rating: 4.7,
    reviewCount: 1023,
    badge: "Bestseller",
    featured: true,
    daysAgo: 260,
    specs: [
      ["Upper", "Full-grain leather"],
      ["Sole", "Stitched rubber cupsole"],
      ["Footbed", "Removable cork"],
      ["Made in", "Portugal"],
    ],
    images: [
      ["1608231387042-66d1773070a5", "Court Classic white leather sneaker on a dark background"],
      ["1600269452121-4f2416e55c28", "Court Classic sneaker on folded clothing"],
      ["1579338559194-a162d19bf842", "Court Classic sneaker on a blue court"],
    ],
  },
  {
    slug: "kinetic-hightop-88-basketball-sneaker",
    name: "Hightop 88 Sneaker",
    brand: "Kinetic",
    category: "footwear",
    shortDescription: "Retro basketball high-top in leather with a padded collar and pivot-point outsole.",
    description:
      "Hightop 88 brings back the shape of late-80s basketball shoes with modern comfort. The tumbled leather upper and padded collar support the ankle, the pivot-point outsole grips any court or pavement, and a foam insole makes it wearable all day.",
    price: 12900,
    compareAt: 15900,
    stock: 44,
    rating: 4.3,
    reviewCount: 362,
    badge: null,
    featured: false,
    daysAgo: 90,
    specs: [
      ["Upper", "Tumbled leather"],
      ["Collar", "Padded high-top"],
      ["Outsole", "Rubber, pivot point"],
      ["Colourways", "Triple white, chicago red"],
    ],
    images: [
      ["1512374382149-233c42b6a83b", "Hightop 88 sneakers in triple white"],
      ["1552346154-21d32810aba3", "Hightop 88 in black, white and red"],
    ],
  },
  {
    slug: "kinetic-retro-suede-runner",
    name: "Retro Suede Runner",
    brand: "Kinetic",
    category: "footwear",
    shortDescription: "70s-inspired lifestyle sneaker in soft suede with a cushioned EVA midsole.",
    description:
      "Retro Suede Runner keeps the silhouette of a classic jogging shoe and swaps the performance tech for everyday comfort. The suede and nylon upper comes in pastel and earthy colourways, and a lightweight EVA midsole keeps it springy from morning coffee to late dinner.",
    price: 9900,
    compareAt: null,
    stock: 95,
    rating: 4.2,
    reviewCount: 281,
    badge: "New",
    featured: false,
    daysAgo: 9,
    specs: [
      ["Upper", "Suede and nylon"],
      ["Midsole", "EVA"],
      ["Outsole", "Rubber waffle"],
      ["Weight", "280 g (US 9)"],
    ],
    images: [
      ["1549298916-b41d501d3772", "Retro Suede Runner in tan suede"],
      ["1551107696-a4b0c5a0d9a2", "Retro Suede Runner in pink and grey"],
      ["1595950653106-6c9ebd614d3a", "Retro Suede Runner in pastel colours"],
    ],
  },
  {
    slug: "fenwick-foundry-leather-work-boot",
    name: "Foundry Leather Work Boot",
    brand: "Fenwick & Co",
    category: "footwear",
    shortDescription: "Goodyear-welted leather boot with a lug sole, built to be resoled for decades.",
    description:
      "Foundry is a boot for the long haul. Oil-tanned leather resists water and develops a deep patina, the Goodyear welt means a cobbler can resole it again and again, and the Vibram lug sole grips on wet streets and gravel paths alike. Expect a short break-in, then years of comfort.",
    price: 27900,
    compareAt: null,
    stock: 26,
    rating: 4.8,
    reviewCount: 311,
    badge: null,
    featured: false,
    daysAgo: 170,
    specs: [
      ["Upper", "Oil-tanned leather"],
      ["Construction", "Goodyear welt"],
      ["Sole", "Vibram lug"],
      ["Lining", "Leather"],
      ["Made in", "Portugal"],
    ],
    images: [
      ["1608256246200-53e635b5b65f", "Foundry work boots in dark brown leather"],
      ["1605812860427-4024433a70fd", "Foundry boot in close-up on a dark background"],
      ["1613673720017-56e42d90fee4", "Foundry boots in black on a doorstep"],
    ],
  },
  {
    slug: "ridgeline-summit-hiking-boot",
    name: "Summit Waterproof Hiking Boot",
    brand: "Ridgeline",
    category: "footwear",
    shortDescription: "Waterproof suede hiking boot with a grippy rubber outsole and ankle support.",
    description:
      "Summit keeps your feet dry and steady from trailhead to ridge. A waterproof, breathable membrane sits under a rugged suede upper, the padded collar supports your ankles on uneven ground, and the deep-lug outsole bites into mud, scree and wet rock.",
    price: 18900,
    compareAt: 21900,
    stock: 37,
    rating: 4.6,
    reviewCount: 458,
    badge: null,
    featured: false,
    daysAgo: 240,
    specs: [
      ["Upper", "Suede and nylon"],
      ["Membrane", "Waterproof, breathable"],
      ["Outsole", "Rubber, 5 mm lugs"],
      ["Weight", "540 g (US 9)"],
      ["Use", "Day hikes, backpacking"],
    ],
    images: [
      ["1599012307605-23a0ebe4d321", "Summit hiking boots with red laces"],
      ["1575987116913-e96e7d490b8a", "Summit hiking boots on a rocky trail"],
      ["1573543794198-73ff121c0a8f", "Well-worn Summit boots on a mountain"],
    ],
  },
  {
    slug: "fenwick-mayfair-chelsea-boot",
    name: "Mayfair Chelsea Boot",
    brand: "Fenwick & Co",
    category: "footwear",
    shortDescription: "Polished leather Chelsea boot with elastic gussets and a slim leather sole.",
    description:
      "Mayfair is a sleek Chelsea boot that dresses up denim and suits alike. Burnished calf leather, elastic side gussets and a pull tab make it easy to slip on, and a slim leather sole with a rubber heel insert keeps the profile elegant without being slippery.",
    price: 22900,
    compareAt: null,
    stock: 19,
    rating: 4.7,
    reviewCount: 204,
    badge: "Staff pick",
    featured: false,
    daysAgo: 40,
    specs: [
      ["Upper", "Burnished calf leather"],
      ["Construction", "Blake stitched"],
      ["Sole", "Leather with rubber heel"],
      ["Made in", "Spain"],
    ],
    images: [
      ["1777987601423-f350ac29b3e9", "Mayfair Chelsea boots in brown leather on wood"],
      ["1777987601677-3059be0e1388", "Mayfair Chelsea boot in polished brown"],
      ["1534233812932-59b8fa1b780c", "Mayfair Chelsea boots in black"],
    ],
  },
  {
    slug: "fenwick-horsebit-leather-loafer",
    name: "Horsebit Leather Loafer",
    brand: "Fenwick & Co",
    category: "footwear",
    shortDescription: "Hand-finished leather loafer with a gold-tone horsebit and a cushioned insole.",
    description:
      "The Horsebit Loafer is an easy way to look put together. Hand-burnished cognac leather, a gold-tone metal bit across the vamp and a flexible leather sole make it as comfortable at a summer wedding as it is at the office. Wear it with or without socks.",
    price: 19900,
    compareAt: 24900,
    stock: 22,
    rating: 4.5,
    reviewCount: 167,
    badge: null,
    featured: false,
    daysAgo: 310,
    specs: [
      ["Upper", "Hand-burnished leather"],
      ["Hardware", "Gold-tone horsebit"],
      ["Sole", "Flexible leather"],
      ["Made in", "Italy"],
    ],
    images: [
      ["1616406432452-07bc5938759d", "Horsebit loafers in cognac leather"],
      ["1615979474401-8a6a344de5bd", "Pair of Horsebit loafers from above"],
      ["1777987601447-266e128de448", "Penny loafer variant on a wooden stool"],
    ],
  },

  // ── Cameras ──────────────────────────────────────────────────────────────────────────────────
  {
    slug: "kestrel-a9-full-frame-mirrorless-camera",
    name: "A9 Full-Frame Mirrorless Camera",
    brand: "Kestrel",
    category: "cameras",
    shortDescription: "33 MP full-frame mirrorless body with in-body stabilisation and 4K 60p video.",
    description:
      "The A9 is a do-everything camera for serious hobbyists and working photographers. Its 33 MP back-illuminated sensor delivers clean files up to ISO 12,800, five-axis in-body stabilisation keeps handheld shots sharp, and real-time eye tracking locks onto people, animals and birds. 4K 60p video with 10-bit colour makes it just as capable for film.",
    price: 249900,
    compareAt: null,
    stock: 8,
    rating: 4.8,
    reviewCount: 389,
    badge: "Bestseller",
    featured: true,
    daysAgo: 130,
    specs: [
      ["Sensor", "33 MP full-frame BSI CMOS"],
      ["Stabilisation", "5-axis IBIS"],
      ["Autofocus", "759-point, AI subject tracking"],
      ["Video", "4K 60p, 10-bit 4:2:2"],
      ["Burst", "10 fps"],
      ["Weight", "658 g (body)"],
    ],
    images: [
      ["1516035069371-29a1b244cc32", "A9 camera body with lenses on a black surface"],
      ["1552233707-a3185320d9a0", "A9 held in hand with a zoom lens"],
      ["1581591524425-c7e0978865fc", "Two A9 bodies under coloured light"],
    ],
  },
  {
    slug: "lumio-x-t50-retro-mirrorless-camera",
    name: "X-T50 Retro Mirrorless Camera",
    brand: "Lumio",
    category: "cameras",
    shortDescription: "Compact APS-C mirrorless camera with classic dials and built-in film simulations.",
    description:
      "X-T50 brings the joy back to photography with dedicated dials for shutter speed, ISO and exposure compensation. The 26 MP APS-C sensor and a set of built-in film simulations give you beautiful JPEGs straight out of camera, and the compact body is light enough to carry every day. Comes with an 18-55 mm kit zoom.",
    price: 119900,
    compareAt: 134900,
    stock: 15,
    rating: 4.7,
    reviewCount: 276,
    badge: null,
    featured: false,
    daysAgo: 70,
    specs: [
      ["Sensor", "26 MP APS-C"],
      ["Controls", "Shutter, ISO and EV dials"],
      ["Video", "4K 30p"],
      ["Kit lens", "18-55 mm f/2.8-4"],
      ["Weight", "448 g (body)"],
    ],
    images: [
      ["1452780212940-6f5c0d14d848", "X-T50 camera with kit lens on a white surface"],
      ["1536632087471-3cf3f2986328", "Top dials of the X-T50"],
      ["1607462109225-6b64ae2dd3cb", "X-T50 held at night with city lights behind"],
    ],
  },
  {
    slug: "kestrel-d780-dslr-camera",
    name: "D780 DSLR Camera",
    brand: "Kestrel",
    category: "cameras",
    shortDescription: "Weather-sealed 24 MP DSLR with an optical viewfinder and a 2,200-shot battery.",
    description:
      "D780 is for photographers who love an optical viewfinder. A 24 MP full-frame sensor, a fast 51-point phase-detect autofocus system and weather sealing make it dependable in any conditions, and the battery lasts more than 2,000 shots per charge. Dual SD slots keep your files safe.",
    price: 149900,
    compareAt: 179900,
    stock: 6,
    rating: 4.6,
    reviewCount: 198,
    badge: null,
    featured: false,
    daysAgo: 360,
    specs: [
      ["Sensor", "24 MP full-frame"],
      ["Viewfinder", "Optical pentaprism, 100%"],
      ["Autofocus", "51-point phase detect"],
      ["Battery life", "2,260 shots (CIPA)"],
      ["Storage", "Dual SD UHS-II"],
    ],
    images: [
      ["1500634245200-e5245c7574ef", "D780 DSLR with a standard zoom lens"],
      ["1614108830714-74f0e4c8cd7e", "D780 with a telephoto lens on a black background"],
    ],
  },
  {
    slug: "lumio-x100-premium-compact-camera",
    name: "X100 Premium Compact Camera",
    brand: "Lumio",
    category: "cameras",
    shortDescription: "Fixed 23 mm f/2 lens compact with a hybrid viewfinder and leaf shutter.",
    description:
      "X100 is the camera that goes everywhere. Its fixed 23 mm f/2 lens is sharp and compact, the hybrid viewfinder switches between optical and electronic views, and the near-silent leaf shutter syncs with flash at any speed. Street, travel and family photography never looked so good from something this small.",
    price: 159900,
    compareAt: null,
    stock: 4,
    rating: 4.9,
    reviewCount: 512,
    badge: "Limited",
    featured: true,
    daysAgo: 25,
    specs: [
      ["Sensor", "40 MP APS-C"],
      ["Lens", "23 mm f/2 (35 mm equivalent)"],
      ["Viewfinder", "Hybrid optical / electronic"],
      ["Shutter", "Leaf, up to 1/4000 s"],
      ["Weight", "521 g"],
    ],
    images: [
      ["1516724562728-afc824a36e84", "X100 compact camera in silver and black"],
      ["1505739998589-00fc191ce01d", "X100 Mini on a yellow background"],
    ],
  },
  {
    slug: "orion-ae-35mm-film-slr",
    name: "AE 35mm Film SLR",
    brand: "Orion Optics",
    category: "cameras",
    shortDescription: "Refurbished 35 mm film SLR with a 50 mm f/1.8 lens and a fresh light seal kit.",
    description:
      "Every AE is a classic 35 mm SLR that has been cleaned, tested and fitted with new light seals by our technicians. Shoot in shutter priority or full manual, enjoy the bright split-prism viewfinder, and pair it with the included 50 mm f/1.8 lens. It runs on a single, easy-to-find battery and comes with a 12-month warranty.",
    price: 32900,
    compareAt: null,
    stock: 5,
    rating: 4.6,
    reviewCount: 142,
    badge: null,
    featured: false,
    daysAgo: 220,
    specs: [
      ["Format", "35 mm film"],
      ["Modes", "Shutter priority, manual"],
      ["Lens", "50 mm f/1.8"],
      ["Condition", "Refurbished, new light seals"],
      ["Warranty", "12 months"],
    ],
    images: [
      ["1491796014055-e6835cdcd4c6", "AE film SLR on the sand under a pier"],
      ["1516852294404-5423eaa0d4a9", "AE in black with a 50 mm lens"],
      ["1595793550800-5bdd9d23b2fa", "AE film camera next to an instant camera and photos"],
    ],
  },
  {
    slug: "orion-rangefinder-classic-film-camera",
    name: "Rangefinder Classic Film Camera",
    brand: "Orion Optics",
    category: "cameras",
    shortDescription: "Restored 1970s 35 mm rangefinder with a sharp 40 mm f/1.7 lens.",
    description:
      "The Rangefinder Classic is small, quiet and fun. Its fixed 40 mm f/1.7 lens is sharp wide open, the coupled rangefinder makes focusing precise, and the leaf shutter barely makes a sound. Each one is restored by hand, with a cleaned lens, new seals and a calibrated rangefinder.",
    price: 21900,
    compareAt: 25900,
    stock: 3,
    rating: 4.4,
    reviewCount: 61,
    badge: null,
    featured: false,
    daysAgo: 340,
    specs: [
      ["Format", "35 mm film"],
      ["Lens", "40 mm f/1.7"],
      ["Focusing", "Coupled rangefinder"],
      ["Shutter", "Leaf, up to 1/500 s"],
      ["Condition", "Restored"],
    ],
    images: [
      ["1516961642265-531546e84af2", "Rangefinder Classic hanging on its strap"],
      ["1524135220673-c731600a1a50", "Rangefinder Classic on a white table"],
    ],
  },
  {
    slug: "polaris-onestep-instant-camera",
    name: "OneStep Instant Camera",
    brand: "Polaris",
    category: "cameras",
    shortDescription: "Point-and-shoot instant camera with a built-in flash and self-timer.",
    description:
      "OneStep turns any moment into a print you can hold within minutes. Point, press and the photo slides out, with a built-in flash for parties and a self-timer for group shots. The rechargeable battery lasts for around fifteen packs of film, and the retro rainbow stripe never goes out of style.",
    price: 9900,
    compareAt: 12900,
    stock: 110,
    rating: 4.3,
    reviewCount: 1430,
    badge: "Bestseller",
    featured: false,
    daysAgo: 100,
    specs: [
      ["Film", "Integral instant film"],
      ["Lens", "Fixed focus"],
      ["Flash", "Built-in"],
      ["Battery", "USB rechargeable, ~15 packs"],
      ["Self-timer", "Yes"],
    ],
    images: [
      ["1526170375885-4d8ecf77b99f", "OneStep instant camera in white"],
      ["1521499672281-c8be7d37d451", "OneStep camera held up against a blue sky"],
      ["1516962126636-27ad087061cc", "OneStep Pronto variant in black"],
    ],
  },
  {
    slug: "kestrel-go-4k-action-camera",
    name: "Go 4K Action Camera",
    brand: "Kestrel",
    category: "cameras",
    shortDescription: "Waterproof 4K action camera with horizon levelling and a front-facing screen.",
    description:
      "Go 4K is ready for the bike, the board and the pool without a housing. It records 4K at 60 fps with electronic stabilisation and horizon levelling so footage stays smooth and straight, and the front screen makes framing vlogs easy. Waterproof to 10 m, with a dive case included for deeper adventures.",
    price: 29900,
    compareAt: null,
    stock: 52,
    rating: 4.5,
    reviewCount: 683,
    badge: "New",
    featured: false,
    daysAgo: 14,
    specs: [
      ["Video", "4K 60p, 2.7K 120p"],
      ["Stabilisation", "Electronic, horizon levelling"],
      ["Screens", "Rear touch + front preview"],
      ["Waterproof", "10 m (60 m with dive case)"],
      ["Weight", "153 g"],
    ],
    images: [
      ["1571190144364-1da84d9ca448", "Go 4K action camera on a handle grip in the mountains"],
      ["1513193643083-07325d25a4b0", "Go 4K in its waterproof dive case"],
      ["1562878671-b3efe27953b9", "Go 4K held in hand"],
    ],
  },
  {
    slug: "orion-50mm-f1-4-prime-lens",
    name: "50mm f/1.4 Prime Lens",
    brand: "Orion Optics",
    category: "cameras",
    shortDescription: "Fast standard prime with creamy bokeh and a quiet stepping autofocus motor.",
    description:
      "A 50 mm prime is the first lens many photographers fall in love with, and this one earns it. The f/1.4 aperture gathers light in dim rooms and melts backgrounds into smooth bokeh, aspherical elements keep it sharp corner to corner, and the stepping motor focuses silently for video.",
    price: 44900,
    compareAt: 49900,
    stock: 20,
    rating: 4.7,
    reviewCount: 233,
    badge: null,
    featured: false,
    daysAgo: 190,
    specs: [
      ["Focal length", "50 mm"],
      ["Maximum aperture", "f/1.4"],
      ["Elements", "12 in 10 groups, 2 aspherical"],
      ["Autofocus", "Stepping motor"],
      ["Filter thread", "67 mm"],
    ],
    images: [
      ["1568840739765-838c480554bb", "50mm prime lens on a white background"],
      ["1580852300513-9b50125bf293", "Front element of the 50mm lens on a dark background"],
      ["1512790182412-b19e6d62bc39", "Close-up of the lens barrel and focus ring"],
    ],
  },
  {
    slug: "orion-24-105mm-f4-zoom-lens",
    name: "24-105mm f/4 Zoom Lens",
    brand: "Orion Optics",
    category: "cameras",
    shortDescription: "Versatile weather-sealed standard zoom with optical stabilisation.",
    description:
      "The 24-105 mm covers wide landscapes to flattering portraits in one lens, making it the ideal travel companion. A constant f/4 aperture keeps exposure consistent through the zoom range, optical stabilisation adds four stops of shake reduction, and weather sealing means a passing shower won't end the shoot.",
    price: 89900,
    compareAt: null,
    stock: 12,
    rating: 4.6,
    reviewCount: 158,
    badge: null,
    featured: false,
    daysAgo: 80,
    specs: [
      ["Focal length", "24-105 mm"],
      ["Maximum aperture", "f/4 constant"],
      ["Stabilisation", "Optical, 4 stops"],
      ["Weather sealing", "Yes"],
      ["Filter thread", "77 mm"],
    ],
    images: [
      ["1593704212686-6d52058fb516", "24-105mm zoom lens on a wooden table"],
      ["1582994254571-52c62d96ebab", "24-105mm lens front element"],
      ["1580707221190-bd94d9087b7f", "24-105mm lens held in hand"],
    ],
  },

  // ── Accessories ──────────────────────────────────────────────────────────────────────────────
  {
    slug: "solenne-classic-square-sunglasses",
    name: "Classic Square Sunglasses",
    brand: "Solenne",
    category: "accessories",
    shortDescription: "Black acetate square frames with polarised lenses and full UV400 protection.",
    description:
      "The Classic Square is the frame that suits almost every face. Hand-polished acetate, sturdy five-barrel hinges and polarised lenses that cut glare off water and roads make it a pair you'll reach for every sunny day. Comes with a hard case and a microfibre cloth.",
    price: 14900,
    compareAt: null,
    stock: 96,
    rating: 4.6,
    reviewCount: 744,
    badge: "Bestseller",
    featured: true,
    daysAgo: 115,
    specs: [
      ["Frame", "Acetate"],
      ["Lenses", "Polarised, UV400"],
      ["Lens width", "52 mm"],
      ["Hinges", "Five-barrel"],
    ],
    images: [
      ["1572635196237-14b3f281503f", "Classic Square sunglasses in black on a white surface"],
      ["1566421966482-ad8076104d8e", "Classic Square sunglasses on the sand"],
      ["1473496169904-658ba7c44d8a", "Classic Square sunglasses at the beach"],
    ],
  },
  {
    slug: "solenne-riviera-round-metal-sunglasses",
    name: "Riviera Round Metal Sunglasses",
    brand: "Solenne",
    category: "accessories",
    shortDescription: "Lightweight gold-tone round frames with green mineral glass lenses.",
    description:
      "Riviera is a nod to 60s Mediterranean summers. The thin gold-tone titanium frame weighs next to nothing, adjustable nose pads give a precise fit, and the green mineral glass lenses render colours naturally while blocking all UVA and UVB light.",
    price: 17900,
    compareAt: 21900,
    stock: 40,
    rating: 4.4,
    reviewCount: 219,
    badge: null,
    featured: false,
    daysAgo: 55,
    specs: [
      ["Frame", "Gold-tone titanium"],
      ["Lenses", "Green mineral glass, UV400"],
      ["Lens width", "49 mm"],
      ["Weight", "21 g"],
    ],
    images: [
      ["1511499767150-a48a237f0083", "Riviera round sunglasses in gold-tone metal"],
      ["1577803645773-f96470509666", "Riviera sunglasses with clear frames by the sea"],
    ],
  },
  {
    slug: "solenne-havana-tortoiseshell-sunglasses",
    name: "Havana Tortoiseshell Sunglasses",
    brand: "Solenne",
    category: "accessories",
    shortDescription: "Bold tortoiseshell acetate frames with gradient brown lenses.",
    description:
      "Havana pairs warm tortoiseshell acetate with gradient brown lenses for a look that works from city streets to beach bars. Spring hinges keep the fit comfortable all day, and the lenses are scratch-resistant and fully UV400 protected.",
    price: 15900,
    compareAt: null,
    stock: 35,
    rating: 4.5,
    reviewCount: 188,
    badge: "New",
    featured: false,
    daysAgo: 8,
    specs: [
      ["Frame", "Tortoiseshell acetate"],
      ["Lenses", "Gradient brown, UV400"],
      ["Lens width", "54 mm"],
      ["Hinges", "Spring"],
    ],
    images: [
      ["1559070081-648fb00b2ed1", "Havana tortoiseshell sunglasses with their box"],
      ["1508296695146-257a814070b4", "Havana cat-eye variant with gradient lenses"],
    ],
  },
  {
    slug: "solenne-browline-sunglasses",
    name: "Browline Sunglasses",
    brand: "Solenne",
    category: "accessories",
    shortDescription: "Half-rim browline frames with a gunmetal bridge and grey gradient lenses.",
    description:
      "Browline combines an acetate brow with a slim gunmetal lower rim for a sharp, intellectual silhouette. Grey gradient lenses keep colours true, and the adjustable nose pads and temple tips make it easy to get a perfect fit.",
    price: 13900,
    compareAt: 16900,
    stock: 28,
    rating: 4.3,
    reviewCount: 97,
    badge: null,
    featured: false,
    daysAgo: 250,
    specs: [
      ["Frame", "Acetate and metal"],
      ["Lenses", "Grey gradient, UV400"],
      ["Lens width", "51 mm"],
    ],
    images: [
      ["1584036553516-bf83210aa16c", "Browline sunglasses on a white surface"],
      ["1653038282189-803202722a05", "Browline sunglasses with dark lenses"],
    ],
  },
  {
    slug: "harbor-leather-heritage-bifold-wallet",
    name: "Heritage Bifold Wallet",
    brand: "Harbor Leather",
    category: "accessories",
    shortDescription: "Vegetable-tanned leather bifold with six card slots and a full-length bill pocket.",
    description:
      "The Heritage Bifold is cut from vegetable-tanned leather that darkens and softens into a rich patina over the years. Six card slots, two hidden pockets and a full-length bill compartment hold everything you need without the bulk. Every edge is burnished and hand-stitched with waxed thread.",
    price: 7900,
    compareAt: null,
    stock: 84,
    rating: 4.7,
    reviewCount: 538,
    badge: "Bestseller",
    featured: true,
    daysAgo: 280,
    specs: [
      ["Material", "Vegetable-tanned leather"],
      ["Card slots", "6 + 2 hidden pockets"],
      ["Dimensions", "11.5 × 9 cm closed"],
      ["Stitching", "Hand-stitched, waxed thread"],
    ],
    images: [
      ["1624538000860-24716b9050f2", "Heritage bifold wallet in tan leather"],
      ["1620109176813-e91290f6c795", "Heritage bifold wallet in aged brown"],
    ],
  },
  {
    slug: "harbor-leather-midnight-slim-wallet",
    name: "Midnight Slim Wallet",
    brand: "Harbor Leather",
    category: "accessories",
    shortDescription: "Slim black leather bifold with RFID protection and room for eight cards.",
    description:
      "Midnight is a slim bifold for front pockets. Smooth black full-grain leather, an RFID-blocking lining and eight card slots arranged in staggered rows keep it thin even when full. It arrives in a gift box, ready to give.",
    price: 6900,
    compareAt: 8900,
    stock: 102,
    rating: 4.5,
    reviewCount: 312,
    badge: null,
    featured: false,
    daysAgo: 145,
    specs: [
      ["Material", "Full-grain leather"],
      ["Card slots", "8"],
      ["RFID blocking", "Yes"],
      ["Thickness", "11 mm empty"],
    ],
    images: [
      ["1612023395494-1c4050b68647", "Midnight slim wallet in black on a table"],
      ["1579014134953-1580d7f123f3", "Midnight wallet with banknotes"],
    ],
  },
  {
    slug: "harbor-leather-card-holder",
    name: "Minimal Card Holder",
    brand: "Harbor Leather",
    category: "accessories",
    shortDescription: "Four-slot leather card holder that fits the tightest pocket.",
    description:
      "For days when you only need a few cards, the Minimal Card Holder is all you carry. Four angled slots and a centre pocket hold up to eight cards and a folded note, and the pebbled leather hides scratches.",
    price: 3900,
    compareAt: null,
    stock: 150,
    rating: 4.4,
    reviewCount: 426,
    badge: null,
    featured: false,
    daysAgo: 65,
    specs: [
      ["Material", "Pebbled leather"],
      ["Capacity", "Up to 8 cards"],
      ["Dimensions", "10 × 7 cm"],
    ],
    images: [
      ["1601592996763-f05c9c80a7f1", "Minimal card holders in black on concrete"],
      ["1676276550349-580c49631496", "Card holder and leather key fob on a wooden table"],
    ],
  },
  {
    slug: "harbor-leather-full-grain-belt",
    name: "Full-Grain Leather Belt",
    brand: "Harbor Leather",
    category: "accessories",
    shortDescription: "35 mm belt cut from a single strip of full-grain leather with a solid brass buckle.",
    description:
      "This belt is made from a single strip of thick full-grain leather, so there is nothing to peel or crack. The solid brass buckle is held with screws, letting you swap it out or resize the belt in seconds. It will outlast every pair of jeans you put it through.",
    price: 8900,
    compareAt: null,
    stock: 61,
    rating: 4.8,
    reviewCount: 274,
    badge: "Staff pick",
    featured: false,
    daysAgo: 175,
    specs: [
      ["Material", "Full-grain leather, 4 mm"],
      ["Width", "35 mm"],
      ["Buckle", "Solid brass, screw-fastened"],
      ["Sizes", "28-44"],
    ],
    images: [
      ["1664286074176-5206ee5dc878", "Full-grain leather belt in dark brown"],
      ["1705493655920-20c572928501", "Leather belt coiled on a wooden floor"],
      ["1624222247344-550fb60583dc", "Close-up of the belt buckle"],
    ],
  },
  {
    slug: "fieldnote-washed-cotton-cap",
    name: "Washed Cotton Cap",
    brand: "Fieldnote",
    category: "accessories",
    shortDescription: "Six-panel cap in garment-washed cotton twill with an adjustable strap.",
    description:
      "The Washed Cotton Cap feels broken-in from day one. Garment-dyed and washed cotton twill gives it a soft, slightly faded look, the curved brim keeps sun out of your eyes, and the adjustable brass-buckle strap fits most heads.",
    price: 3400,
    compareAt: 4400,
    stock: 140,
    rating: 4.3,
    reviewCount: 205,
    badge: null,
    featured: false,
    daysAgo: 35,
    specs: [
      ["Material", "100% cotton twill"],
      ["Panels", "6"],
      ["Closure", "Adjustable strap, brass buckle"],
      ["Colours", "Washed black, white, mustard"],
    ],
    images: [
      ["1521369909029-2afed882baee", "Washed cotton cap in faded black"],
      ["1691256676359-20e5c6d4bc92", "Cap in white on a grey background"],
      ["1645266729222-17cd32e06fd0", "Cap in mustard yellow"],
    ],
  },
  {
    slug: "fieldnote-merino-rib-beanie",
    name: "Merino Rib Beanie",
    brand: "Fieldnote",
    category: "accessories",
    shortDescription: "Soft ribbed beanie knitted from extra-fine merino wool.",
    description:
      "Knitted from extra-fine merino, this beanie is warm without itching and breathes well on brisk walks. The deep rib and fold-over cuff let you wear it slouchy or snug, and the yarn is naturally odour-resistant. Available in charcoal, blaze orange and mustard.",
    price: 3900,
    compareAt: null,
    stock: 0,
    rating: 4.6,
    reviewCount: 158,
    badge: "New",
    featured: false,
    daysAgo: 2,
    specs: [
      ["Material", "100% extra-fine merino wool"],
      ["Knit", "2 × 2 rib, fold-over cuff"],
      ["Colours", "Charcoal, blaze orange, mustard"],
    ],
    images: [
      ["1618354691792-d1d42acfd860", "Merino beanie in charcoal"],
      ["1511500118080-275313ec90a1", "Merino beanie in blaze orange"],
      ["1630691650107-53dd500d2907", "Merino beanie in mustard"],
    ],
  },

  // ── Bags ─────────────────────────────────────────────────────────────────────────────────────
  {
    slug: "tern-commuter-backpack-22l",
    name: "Commuter Backpack 22L",
    brand: "Tern & Co",
    category: "bags",
    shortDescription: "Water-resistant everyday backpack with a padded 16\" laptop sleeve.",
    description:
      "The Commuter 22L is organised for the workday. A padded, suspended sleeve protects laptops up to 16 inches, a quick-access top pocket keeps keys and earbuds handy, and the water-resistant recycled fabric shrugs off rain on the walk to the station. A luggage pass-through slides it onto a suitcase handle.",
    price: 12900,
    compareAt: null,
    stock: 70,
    rating: 4.6,
    reviewCount: 811,
    badge: "Bestseller",
    featured: true,
    daysAgo: 125,
    specs: [
      ["Capacity", "22 L"],
      ["Laptop sleeve", "Up to 16\""],
      ["Material", "Recycled polyester, water-resistant"],
      ["Weight", "0.9 kg"],
    ],
    images: [
      ["1553062407-98eeb64c6a62", "Commuter backpack in navy on a white floor"],
      ["1581605405669-fcdf81165afa", "Commuter backpack in black held by its handle"],
    ],
  },
  {
    slug: "harbor-leather-heritage-leather-backpack",
    name: "Heritage Leather Backpack",
    brand: "Harbor Leather",
    category: "bags",
    shortDescription: "Full-grain leather backpack with brass zips and a padded laptop compartment.",
    description:
      "The Heritage Backpack is made from thick full-grain leather that only gets better with time. A padded compartment holds a 15-inch laptop, front and side pockets keep smaller things organised, and solid brass zips glide smoothly for years. Each piece is slightly different thanks to the natural grain.",
    price: 34900,
    compareAt: 39900,
    stock: 13,
    rating: 4.8,
    reviewCount: 196,
    badge: null,
    featured: false,
    daysAgo: 155,
    specs: [
      ["Material", "Full-grain leather"],
      ["Capacity", "18 L"],
      ["Laptop sleeve", "Up to 15\""],
      ["Hardware", "Solid brass zips"],
      ["Weight", "1.6 kg"],
    ],
    images: [
      ["1622560480605-d83c853bc5c3", "Heritage leather backpack in cognac"],
      ["1622560257067-108402fcedc0", "Heritage backpack from the side"],
      ["1622560480654-d96214fdc887", "Heritage backpack in oxblood"],
    ],
  },
  {
    slug: "ridgeline-alpine-35-hiking-pack",
    name: "Alpine 35 Hiking Pack",
    brand: "Ridgeline",
    category: "bags",
    shortDescription: "Ventilated 35 L day-hiking pack with a hip belt and integrated rain cover.",
    description:
      "Alpine 35 carries everything for a long day in the hills. The suspended mesh back panel keeps air moving, a padded hip belt takes weight off your shoulders, and the integrated rain cover tucks away in its own pocket. Trekking pole loops and a hydration sleeve complete the kit.",
    price: 15900,
    compareAt: null,
    stock: 31,
    rating: 4.7,
    reviewCount: 367,
    badge: null,
    featured: false,
    daysAgo: 205,
    specs: [
      ["Capacity", "35 L"],
      ["Back system", "Suspended mesh"],
      ["Rain cover", "Integrated"],
      ["Hydration", "Sleeve, up to 3 L"],
      ["Weight", "1.2 kg"],
    ],
    images: [
      ["1622260614153-03223fb72052", "Alpine 35 pack in forest green on a rock"],
      ["1622260614927-208cfe3f5cfd", "Alpine 35 pack by a river"],
      ["1509762774605-f07235a08f1f", "Alpine 35 in grey on a ridge at sunset"],
    ],
  },
  {
    slug: "tern-waxed-canvas-rucksack",
    name: "Waxed Canvas Rucksack",
    brand: "Tern & Co",
    category: "bags",
    shortDescription: "Waxed canvas rucksack with leather straps and a roomy drawstring main compartment.",
    description:
      "This rucksack is cut from heavyweight waxed canvas that repels rain and ages beautifully. Leather buckle straps close the flap over a drawstring main compartment, side pockets hold a bottle and an umbrella, and an inner sleeve fits a 14-inch laptop. Re-wax it once a season and it will last for decades.",
    price: 18900,
    compareAt: 22900,
    stock: 24,
    rating: 4.5,
    reviewCount: 143,
    badge: null,
    featured: false,
    daysAgo: 290,
    specs: [
      ["Material", "Waxed cotton canvas, leather trim"],
      ["Capacity", "20 L"],
      ["Laptop sleeve", "Up to 14\""],
      ["Closure", "Flap with buckles, drawstring"],
    ],
    images: [
      ["1547949003-9792a18a2601", "Waxed canvas rucksack in charcoal with leather straps"],
      ["1577733975197-3b950ca5cabe", "Waxed canvas rucksack on a city street"],
      ["1642375352634-ad952121fdb3", "Rucksack in navy on a white pedestal"],
    ],
  },
  {
    slug: "harbor-leather-oxford-satchel",
    name: "Oxford Leather Satchel",
    brand: "Harbor Leather",
    category: "bags",
    shortDescription: "Classic leather satchel with twin buckles and an adjustable shoulder strap.",
    description:
      "The Oxford Satchel is a timeless shape for daily carry. Two buckled front pockets, a main compartment for a 13-inch laptop and a removable shoulder strap make it work as a briefcase or a crossbody. The leather is drum-dyed so it stays rich even when scratched.",
    price: 22900,
    compareAt: null,
    stock: 17,
    rating: 4.7,
    reviewCount: 221,
    badge: "Staff pick",
    featured: false,
    daysAgo: 135,
    specs: [
      ["Material", "Drum-dyed leather"],
      ["Laptop", "Up to 13\""],
      ["Strap", "Removable, adjustable"],
      ["Dimensions", "38 × 28 × 10 cm"],
    ],
    images: [
      ["1473188588951-666fce8e7c68", "Oxford satchel in tan leather on stone"],
      ["1603219527847-24c87f552a77", "Oxford satchel in dark brown on a wooden stool"],
      ["1605733513597-a8f8341084e6", "Oxford satchel in grey with gold buckles"],
    ],
  },
  {
    slug: "tern-field-canvas-messenger-bag",
    name: "Field Canvas Messenger Bag",
    brand: "Tern & Co",
    category: "bags",
    shortDescription: "Washed canvas messenger with leather trim and plenty of pockets.",
    description:
      "The Field Messenger is a relaxed everyday bag. Washed cotton canvas, leather straps and antiqued buckles give it a lived-in look from the first day, and the inside has pockets for a tablet, notebooks, pens and a phone. The wide strap spreads the load across your shoulder.",
    price: 8900,
    compareAt: 10900,
    stock: 46,
    rating: 4.2,
    reviewCount: 118,
    badge: null,
    featured: false,
    daysAgo: 320,
    specs: [
      ["Material", "Washed cotton canvas, leather trim"],
      ["Fits", "Tablet up to 12.9\""],
      ["Strap", "Wide, adjustable"],
    ],
    images: [
      ["1571689936114-b16146c9570a", "Field messenger bag in grey canvas"],
      ["1528976915572-6a0cf746802e", "Field messenger in sand on dry grass"],
    ],
  },
  {
    slug: "harbor-leather-weekender-duffel",
    name: "Weekender Leather Duffel",
    brand: "Harbor Leather",
    category: "bags",
    shortDescription: "Cabin-size leather duffel with a separate shoe pocket and a padded shoulder strap.",
    description:
      "The Weekender holds two or three days of clothes and still fits in an overhead bin. Full-grain leather handles and body, a zipped shoe pocket at one end and a padded detachable strap make travel easy, and the cotton lining is tough enough for years of trips.",
    price: 29900,
    compareAt: 34900,
    stock: 10,
    rating: 4.8,
    reviewCount: 172,
    badge: null,
    featured: true,
    daysAgo: 50,
    specs: [
      ["Material", "Full-grain leather"],
      ["Capacity", "40 L, cabin size"],
      ["Pockets", "Shoe pocket, interior zip pocket"],
      ["Dimensions", "52 × 28 × 26 cm"],
    ],
    images: [
      ["1525103504173-8dc1582c7430", "Weekender duffel in dark brown on an empty road"],
      ["1448582649076-3981753123b5", "Weekender duffel in tan on a wooden floor"],
    ],
  },
  {
    slug: "fieldnote-organic-canvas-tote",
    name: "Organic Canvas Tote",
    brand: "Fieldnote",
    category: "bags",
    shortDescription: "Heavyweight organic cotton tote with long handles and an inside pocket.",
    description:
      "A tote that is actually built to last: 14 oz organic cotton canvas, reinforced handles long enough to carry on the shoulder, and an inner pocket for keys. It folds flat into a drawer and carries a full grocery run without complaint.",
    price: 2900,
    compareAt: null,
    stock: 200,
    rating: 4.4,
    reviewCount: 392,
    badge: null,
    featured: false,
    daysAgo: 15,
    specs: [
      ["Material", "14 oz organic cotton canvas"],
      ["Dimensions", "38 × 42 cm"],
      ["Handle drop", "28 cm"],
    ],
    images: [
      ["1574365569389-a10d488ca3fb", "Organic canvas tote in natural on a grey wall"],
      ["1630381260512-e3fe55c11973", "Canvas tote carried by hand"],
      ["1548863227-3af567fc3b27", "Printed canvas tote hanging on a wall"],
    ],
  },
  {
    slug: "harbor-leather-market-tote",
    name: "Market Leather Tote",
    brand: "Harbor Leather",
    category: "bags",
    shortDescription: "Unlined leather tote with a magnetic closure, big enough for a laptop.",
    description:
      "The Market Tote is a simple, beautiful bag in soft unlined leather. It swallows a laptop, a jumper and lunch, closes with a hidden magnet, and has a small zipped pocket inside for valuables. The leather is supple from day one and only gets softer.",
    price: 19900,
    compareAt: null,
    stock: 15,
    rating: 4.6,
    reviewCount: 134,
    badge: "New",
    featured: false,
    daysAgo: 4,
    specs: [
      ["Material", "Unlined full-grain leather"],
      ["Closure", "Magnetic"],
      ["Fits", "Laptop up to 15\""],
      ["Dimensions", "40 × 33 × 14 cm"],
    ],
    images: [
      ["1624687943971-e86af76d57de", "Market leather tote in cognac hanging on a wall"],
      ["1598532163257-ae3c6b2524b6", "Woven leather tote variant with a chain"],
    ],
  },
  {
    slug: "bowline-carina-top-handle-bag",
    name: "Carina Top-Handle Bag",
    brand: "Bowline",
    category: "bags",
    shortDescription: "Structured leather top-handle bag with a twist lock and detachable strap.",
    description:
      "Carina is a structured bag with a polished silhouette. A smooth leather body, a silver-tone twist lock and a detachable crossbody strap let it move from desk to dinner. Inside, a slip pocket and a zipped pocket keep cards and keys in place.",
    price: 24900,
    compareAt: 29900,
    stock: 9,
    rating: 4.5,
    reviewCount: 88,
    badge: "Limited",
    featured: false,
    daysAgo: 22,
    specs: [
      ["Material", "Smooth leather"],
      ["Closure", "Twist lock"],
      ["Strap", "Detachable crossbody"],
      ["Dimensions", "24 × 20 × 11 cm"],
    ],
    images: [
      ["1584917865442-de89df76afd3", "Carina top-handle bag in red leather"],
      ["1590874103328-eac38a683ce7", "Carina in orange with a woven body"],
    ],
  },
]
